config_version: 0.3
genome_folder: $GENOMES
genome_archive_folder: $GENOMES/archive
genome_archive_config: master_archive.yaml
genome_servers: ['http://refgenomes.databio.org']
remote_url_base: http://cloud.databio.org/refgenomes/
genomes:
  demo1:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            seek_keys:
              fasta: demo1.fa
              fai: demo1.fa.fai
              chrom_sizes: demo1.chrom.sizes
            asset_digest: 178e1ec13ee8b2b53c67e68f618b6dbf
            asset_parents: []
        default_tag: default
    genome_digest: fa7f432a0ca2a8bb224562f1c2f091e37937c4b0a5f5acf7
    genome_description: d1
  demo2:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            seek_keys:
              fasta: demo2.fa
              fai: demo2.fa.fai
              chrom_sizes: demo2.chrom.sizes
            asset_digest: 095c8035e756f9c589a7485c2f465f1c
            asset_parents: []
        default_tag: default
    genome_digest: 6f2e5266e233ef82ae4fa15fb621ed2843b19cbb5f099391
    genome_description: d2
  demo3:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            seek_keys:
              fasta: demo3.fa
              fai: demo3.fa.fai
              chrom_sizes: demo3.chrom.sizes
            asset_digest: ba86502af816164011d20f0e8c4de1a7
            asset_parents: []
        default_tag: default
    genome_digest: 52c0a74bf4afa6dcfc96531f9f1215f270a014421e0f3852
