config_version: 0.3
genome_folder: $GENOMES
genome_archive_folder: $GENOMES/archive
genome_archive_config: master_archive.yaml
genome_servers: ['http://refgenomes.databio.org']
remote_url_base: http://cloud.databio.org/refgenomes/
genomes: null
